#ifndef MESSAGER_GENERAL_RESOURCE_H
#define MESSAGER_GENERAL_RESOURCE_H

#define USER_MAX 32
#define USERNAME_MAX 32
#define MESSAGE_MAX 64
#define MESSAGE_LEN_MAX 256
#define QUEUE_NAME_LEN_MAX 64

#define BUF_MAX 512
#define TIMEOUT 4

#endif  // MESSAGER_GENERAL_RESOURCE_H