all: exc1 exc2 exc3 exc4

exc1: exc_1.c
	gcc exc_1.c -o exc1
	echo "Вывести двоичное представление целого положительного числа, используя битовые операции"
	./exc1

exc2: exc_2.c
	gcc exc_2.c -o exc2
	echo "Вывести двоичное представление целого положительного числа, используя битовые операции"
	./exc2

exc3: exc_3.c
	gcc exc_3.c -o exc3
	./exc3

exc4: exc_4.c
	gcc exc_4.c -o exc4
	./exc4

clean:
	rm -f exc1 exc2 exc3 exc4